server:
  port: 8082

spring:
  application:
    name: pessoa

  profiles:
    active: local

---

spring:
  config:
    activate:
      on-profile: local
  cloud:
    aws:
      region:
        static: us-east-1
      credentials:
        access-key: test
        secret-key: test
      sqs:
        endpoint: http://localhost:4566

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9997/realms/pessoa-realm

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    path: /swagger-ui/index.html

---

spring:
  config:
    activate:
      on-profile: aws
  cloud:
    aws:
      region:
        static: us-east-1
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9997/realms/pessoa-realm

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    path: /swagger-ui/index.html